### ISSUE TITLE
Error related to SSH on Cent OS server

### ISSUE THREAD

**Issue by adambarthelson** [sorenrix/terraform-aws-centos-jenkins#1]
```
Error: Error applying plan:

1 error(s) occurred:

* module.centos-jenkins.aws_instance.jenkins_server: timeout - last error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [publickey none], no supported methods remain
```

**Comment by rf-sys** [comment]
Hi! Sorry, i haven't noticed your issue.
I've tested it right now and it works fine for me.

My configuration:
https://gist.github.com/salvatoris/f45e717433a6f09482963fbd01d24206

Output:
https://gist.github.com/salvatoris/1de5b5408303eb554305a876aa0ce846

I think the problem is that the module wasn't able to retrieve your ssh key(s) and, hence, it threw an error trying to authenticate with those keys. Maybe, you have incorrect ssh public/private key path or read permission problem.
